# Generated by Django 3.0.7 on 2020-06-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Board',
            new_name='board',
        ),
    ]
